name: the/reader
version: 1.0.0
description: The Programming Language reader
license: MIT
main: src/reader

packages:
  the/error: 1.0.0
  the/testing: 0.1.0

scripts:
  test: the build && the run build/result
