name: the/args
version: 0.1.0
description: Command line arguments parser and tools
license: MIT
main: src/args

packages:
  the/error: 1.0.0
  the/testing: 0.1.0

scripts:
  test: the build && the run build/result
