name: the/parser
version: 0.3.3
description: The programming language parser
license: MIT
main: src/main

packages:
  the/testing: 0.3.0

scripts:
  update-tokenizer-tests: the run scripts/update-tokenizer-tests
