name: the/parser
version: 0.1.0
description: The Programming Language parser
license: MIT
main: src/parser

packages:
  - the/error: 1.0.0
  - the/reader: 1.0.0

scripts:
  test: the build && the run build/result
