name: the/analyzer
version: 0.1.0
description: The programming language analyzer
license: MIT
main: src/main

packages:
  the/example: 1.0.1
  the/parser: 0.4.16
  the/testing: 0.4.0

scripts:
  precompile-api: the run scripts/precompile-api
  precompile-builtin: the run scripts/precompile-builtin
  update-print-tests: the run scripts/update-print-tests
  update-type-casting-tests: the run scripts/update-type-casting-tests
