on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ubuntu:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set variables
        run: echo "DOCKER_TAG=${GITHUB_REF#refs/heads/}:$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      - name: Build
        run: docker build -t $DOCKER_TAG .
      - name: Test
        run: docker run $DOCKER_TAG
