name: Packages

on:
  push:
    branches: ['main', 'release-*']
    paths-ignore: ['**/*.md', '**/*.yml', '!.github/workflows/packages.yml']
  pull_request:
    paths-ignore: ['**/*.md', '**/*.yml', '!.github/workflows/packages.yml']

concurrency:
  cancel-in-progress: true
  group: packages-${{ github.event.pull_request.number || github.sha }}

jobs:
  packages:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: macos-13
          - os: ubuntu-22.04
          - os: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: thelang-io/setup-the@v1
      - run: the -v
      - run: (cd packages/algorithm && the test test)
      - run: (cd packages/parser && the test test)
