name: Release

on:
  workflow_dispatch:
  release:
    types: ['published']

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: cmake -B ./build -D CMAKE_BUILD_TYPE=Release
      - run: cmake --build build
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_S3_REGION }}
      - run: aws s3 cp build/the s3://${{ secrets.AWS_S3_BUCKET }}/the-${{ github.event.release.tag_name }} --content-type application/octet-stream
