name: Test Windows

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ["windows-2019", "windows-2022"]
    steps:
      - uses: actions/checkout@v2
      - run: choco install ninja
      - run: mkdir -p build
      - run: cmake . -B ./build -G "Ninja" -D BUILD_TESTS=ON
      - run: cmake --build build
      - run: ctest --output-on-failure --test-dir build
