name: Test Windows

on:
  push:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: choco install ninja
      - run: mkdir -p build
      - run: cmake . -B ./build -G "Ninja" -D BUILD_TESTS=ON
      - run: cmake --build build
      - run: ctest --output-on-failure --test-dir build
