name: Test

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - "**.yml"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.yml"

concurrency:
  cancel-in-progress: true
  group: test-${{ github.event.pull_request.number || github.sha }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12, ubuntu-20.04, ubuntu-22.04, windows-2022]
    steps:
      - uses: actions/checkout@v2

      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install ninja-build valgrind
      - if: runner.os == 'macOS'
        run: brew install ninja

      - if: runner.os == 'Linux'
        run: |
          curl -fsSL https://cdn.thelang.io/packages.tar.gz | tar -xzf
          echo "PACKAGES_DIR=$PWD/the/linux" >> $GITHUB_ENV
      - if: runner.os == 'Windows'
        run: |
          curl -fsSL https://cdn.thelang.io/packages.tar.gz | tar -xzf - -C "C:/Program Files"
          echo "PACKAGES_DIR=C:/Program Files/the/windows" >> $env:GITHUB_ENV
      - if: runner.os == 'macOS'
        run: |
          curl -fsSL https://cdn.thelang.io/packages.tar.gz | tar -xzf
          echo "PACKAGES_DIR=$PWD/the/macos" >> $GITHUB_ENV

      - run: mkdir -p build
      - if: runner.os == 'Linux'
        run: cmake . -B ./build -G "Ninja" -D BUILD_TESTS=ON -D TEST_CODEGEN_MEMCHECK=ON
      - if: runner.os == 'Windows'
        run: cmake . -B ./build -G "Visual Studio 17 2022" -D BUILD_TESTS=ON
      - if: runner.os == 'macOS'
        run: cmake . -B ./build -G "Ninja" -D BUILD_TESTS=ON
      - run: cmake --build build
      - run: ctest --output-on-failure --test-dir build
