name: Test

on:
  push:
    paths-ignore:
      - "**.md"
      - "**.yml"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.yml"

concurrency:
  cancel-in-progress: true
  group: test-${{ github.event.pull_request.number || github.sha }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12, ubuntu-20.04, ubuntu-22.04, windows-2022]
    steps:
      - uses: actions/checkout@v2
      - if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build valgrind
      - if: runner.os == 'Windows'
        run: |
          choco install openssl
          echo "CFLAGS=-LC:\Program Files\OpenSSL-Win64\include" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          echo "LDFLAGS=-LC:\Program Files\OpenSSL-Win64\lib" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      - if: runner.os == 'macOS'
        run: |
          brew install ninja
          echo "CFLAGS=-I/usr/local/opt/openssl@1.1/include" >> $GITHUB_ENV
          echo "LDFLAGS=-L/usr/local/opt/openssl@1.1/lib" >> $GITHUB_ENV
      - run: mkdir -p build
      - if: runner.os == 'Linux'
        run: cmake . -B ./build -G "Ninja" -D BUILD_TESTS=ON -D TEST_CODEGEN_MEMCHECK=ON
      - if: runner.os == 'Windows'
        run: cmake . -B ./build -G "Visual Studio 17 2022" -D BUILD_TESTS=ON
      - if: runner.os == 'macOS'
        run: cmake . -B ./build -G "Ninja" -D BUILD_TESTS=ON
      - run: cmake --build build
      - run: ctest --output-on-failure --test-dir build
