name: Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ["macos-11", "macos-12", "ubuntu-20.04", "ubuntu-22.04", "windows-2019", "windows-2022"]
    steps:
      - uses: actions/checkout@v2
      - run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install ninja-build valgrind
          elif [ "$RUNNER_OS" == "Windows" ]; then
            choco install ninja
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install ninja
          fi
      - run: mkdir -p build
      - run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            cmake . -B ./build -G "Ninja" -D BUILD_TESTS=ON -D TEST_CODEGEN_MEMCHECK=ON
          else
            cmake . -B ./build -G "Ninja" -D BUILD_TESTS=ON
          fi
      - run: cmake --build build
      - run: ctest --output-on-failure --test-dir build
