name: Test

on:
  push:
    branches: ['main', 'release-*']
    paths-ignore: ['**/*.md', '**/*.yml', 'packages/**/*', '!.github/workflows/test.yml']
  pull_request:
    paths-ignore: ['**/*.md', '**/*.yml', 'packages/**/*', '!.github/workflows/test.yml']

concurrency:
  cancel-in-progress: true
  group: test-${{ github.event.pull_request.number || github.sha }}

jobs:
  test:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: macos-13
            platform: macos
            generator: Ninja
          - os: macos-14
            platform: macos
            generator: Ninja
          - os: macos-15
            platform: macos
            generator: Ninja
          - os: ubuntu-20.04
            platform: linux
            generator: Ninja
            memcheck: memcheck
          - os: ubuntu-22.04
            platform: linux
            generator: Ninja
            memcheck: memcheck
          - os: ubuntu-24.04
            platform: linux
            generator: Ninja
            memcheck: memcheck
          - os: windows-2019
            platform: windows
            generator: Visual Studio 16 2019
          - os: windows-2022
            platform: windows
            generator: Visual Studio 17 2022
          - os: windows-2025
            platform: windows
            generator: Visual Studio 17 2022
    steps:
      - uses: actions/checkout@v4
      - if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build valgrind
      - if: runner.os == 'macOS'
        run: brew install ninja
      - if: runner.os != 'Windows'
        run: uname -a
      - run: curl -fsSL https://cdn.thelang.io/deps.tar.gz -o deps.tar.gz
      - run: tar -xzf deps.tar.gz the/native/${{ matrix.config.platform }}
      - if: runner.os == 'Linux'
        run: echo "THE_DEPS_DIR=$PWD/the/native/${{ matrix.config.platform }}" >> $GITHUB_ENV
      - if: runner.os == 'macOS'
        run: echo "THE_DEPS_DIR=$PWD/the/native/${{ matrix.config.platform }}/$(uname -m)" >> $GITHUB_ENV
      - if: runner.os == 'Windows'
        run: echo "THE_DEPS_DIR=$PWD/the/native/${{ matrix.config.platform }}" | Out-File -FilePath $env:GITHUB_ENV -Append
      - if: matrix.config.memcheck != 'memcheck'
        run: cmake . -B ./build -G "${{ matrix.config.generator }}" -D BUILD_TESTS=ON
      - if: matrix.config.memcheck == 'memcheck'
        run: cmake . -B ./build -G "${{ matrix.config.generator }}" -D BUILD_TESTS=ON -D TEST_CODEGEN_MEMCHECK=ON
      - run: cmake --build build
      - run: ctest --output-on-failure --test-dir build
